books_are_fun_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from rango import views
from registration.backends.simple.views import RegistrationView
from django.urls import reverse


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')


urlpatterns = [
        path('admin/', admin.site.urls),
        path('', include('rango.urls'), name='index'),
        
        # New line below -- don't forget the slash after register!
        path('accounts/register/',
            MyRegistrationView.as_view(),
            name='registration_register'),
        
        path('accounts/', include('registration.backends.simple.urls')),
        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    
    path('about/', views.AboutView.as_view(), name='about'),

    path('contact_us/', views.contact_us, name='contact_us'),

    path('register_profile/', views.RegisterProfileView.as_view(), name='register_profile'),

    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),

    path('delete/<username>', views.delete_account, name='delete_account'),

    path('profiles/', views.ListProfilesView.as_view(), name='list_profiles'),

    path('search/', views.SearchResultsView.as_view(), name='search_results'),

    path('add_book/', views.AddBookView.as_view(), name='add_book'),

    path('books/', views.list_books, name='books'),

    path('like_review/', views.LikeReviewView.as_view(), name='like_review'),

    path('dislike_review/', views.DislikeReviewView.as_view(), name='dislike_review'),

    path('<slug:book_title_slug>/', views.ShowBookView.as_view(), name='show_book'),

    path('<slug:book_title_slug>/leave_review/',
         views.LeaveReviewView.as_view(), name='leave_review'),

]

rango/models.py
import datetime
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator, MinLengthValidator, int_list_validator


class Book(models.Model):
    # FK Relationships

    # Max Length Values
    ISBN_MAX_LENGTH = 13
    TITLE_MAX_LENGTH = 128
    DESC_MAX_LENGTH = 1000
    AUTHOR_MAX_LENGTH = 50
    PUB_MAX_LENGTH = 50
    LANG_MAX_LENGTH = 50
    SCORE_MAX_LENGTH = 50

    # Attributes
    isbn = models.CharField(max_length=ISBN_MAX_LENGTH, validators=[MinLengthValidator(13), int_list_validator(sep='')])
    title = models.CharField(max_length=TITLE_MAX_LENGTH, unique=True)
    description = models.TextField(max_length=DESC_MAX_LENGTH)
    author = models.CharField(max_length=AUTHOR_MAX_LENGTH)
    publisher = models.CharField(max_length=PUB_MAX_LENGTH)
    language = models.CharField(max_length=LANG_MAX_LENGTH)
    price = models.DecimalField(default=0, decimal_places=2, max_digits=10)
    bookPicture = models.ImageField(blank=True)
    score = models.FloatField(default=0)

    # Slug
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Book, self).save(*args, **kwargs)

    def updateScore(self, book):
        reviews = book.review_set.all()
        numberOfReviews = len(reviews)

        if(numberOfReviews != 0):
            sum = 0

            for r in reviews:
                sum += r.rating
            
            self.score = sum/numberOfReviews
            self.save()

    # To string
    def __str__(self):
        return self.title


class Review(models.Model):
    # FK Relationships
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # Max Length Values
    TITLE_MAX_LENGTH = 50
    COMM_MAX_LENGTH = 1000

    # Attributes
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    rating = models.IntegerField(default=0,validators=[MinValueValidator(0), MaxValueValidator(5)])
    comment = models.TextField(max_length=COMM_MAX_LENGTH, blank=True)
    publishDate = models.DateField(default=datetime.date.today)
    upvotes = models.IntegerField(default=0)

    # Slug
    slug = models.SlugField(unique=True)

    # Links user and book so that a user cannot have more than 1 review per book
    class Meta:
        unique_together = ('book','user')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Review, self).save(*args, **kwargs)
        self.book.updateScore(book=self.book)

    
    # To string
    def __str__(self):
        return self.title


class UserProfile(models.Model):
    # FK Relationships
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Attributes
    picture = models.ImageField(blank=True)
    joinDate = models.DateField(default=datetime.date.today)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Review, Book, UserProfile
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator, MinLengthValidator, int_list_validator


class BookForm(forms.ModelForm):
    title = forms.CharField(max_length=Book.TITLE_MAX_LENGTH,
                                    help_text="Please enter the book title.")

    isbn = forms.CharField(validators=[MinLengthValidator(13), int_list_validator(sep='', message="ISBN consists of only 13 digits")],
                                    max_length=Book.ISBN_MAX_LENGTH, 
                                    help_text="Please enter the book ISBN (must be 13 digits long).")

    description = forms.CharField(widget=forms.Textarea, max_length=Book.DESC_MAX_LENGTH,
                                    help_text="Please enter the book description.")

    author = forms.CharField(max_length=Book.AUTHOR_MAX_LENGTH,
                                    help_text="Please enter the book author.")

    publisher = forms.CharField(max_length=Book.PUB_MAX_LENGTH,
                                    help_text="Please enter the book publisher.")

    language = forms.CharField(max_length=Book.LANG_MAX_LENGTH,
                                    help_text="Please enter the book language.")

    price = forms.DecimalField(help_text="Please enter the book price (without '£').")

    class Meta:
        model = Book
        fields = ('title','isbn', 'description', 'author', 'publisher', 'language', 'price')


class ReviewForm(forms.ModelForm):
    title = forms.CharField(max_length=Review.TITLE_MAX_LENGTH,
                                    help_text="Enter a title for your review")
    
    rating = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)],
                                    help_text="Enter a score between 0 and 5")
    
    comment = forms.CharField(widget=forms.Textarea, max_length=Review.COMM_MAX_LENGTH,
                                    help_text="Enter your review")
    
    class Meta:
        model = Review
        fields = ['title', 'rating', 'comment',]


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)

rango/views.py
from django.db import IntegrityError
from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Book, Review
from rango.forms import BookForm, ReviewForm, UserProfileForm
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime
from rango.bing_search import run_query
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from rango.models import UserProfile
from django.views.generic import ListView
from django.db.models import Q



class IndexView(View):
    def get(self, request):
        book_list = Book.objects.order_by('-score')[:5]
        review_list = Review.objects.order_by('-upvotes')[:5]

        context_dict = {}
        context_dict['boldmessage'] = 'What book are you going to read today?'
        context_dict['books'] = book_list
        context_dict['reviews'] = review_list
        
        visitor_cookie_handler(request)

        response = render(request, 'rango/index.html', context=context_dict)

        return response


class AboutView(View):
    def get(self, request):
        context_dict = {}

        visitor_cookie_handler(request)
        context_dict['visits'] = request.session['visits']

        response = render(request, 'rango/about.html', context=context_dict)
        return response


class ShowBookView(View):
    def create_context_dict(self, book_title_slug):
        context_dict = {}

        try:
            book = Book.objects.get(slug=book_title_slug)
            reviews = Review.objects.filter(book=book).order_by('-upvotes')

            context_dict['reviews'] = reviews
            context_dict['book'] = book
        except Book.DoesNotExist:
            context_dict['reviews'] = None
            context_dict['book'] = None
        
        return context_dict
    
    def get(self, request, book_title_slug):
        context_dict = self.create_context_dict(book_title_slug)
        return render(request, 'rango/book.html', context_dict)
    
    @method_decorator(login_required)
    def post(self, request, book_title_slug):
        context_dict = self.create_context_dict(book_title_slug)
        query = request.POST['query'].strip()

        if query:
            context_dict['result_list'] = run_query(query)
            context_dict['query'] = query
        
        return render(request, 'rango/book.html', context_dict)


class AddBookView(View):
    @method_decorator(login_required)
    def get(self, request):
        form = BookForm()
        return render(request, 'rango/add_book.html', {'form': form})
    
    @method_decorator(login_required)
    def post(self, request):
        form = BookForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('rango:index'))
        else:
            print(form.errors)
        
        return render(request, 'rango/add_book.html', {'form': form})


class LeaveReviewView(View):
    def get_book_title(self, book_title_slug):
        try:
            book = Book.objects.get(slug=book_title_slug)
        except Book.DoesNotExist:
            book = None
        
        return book
    
    @method_decorator(login_required)
    def get(self, request, book_title_slug):
        form = ReviewForm()
        book = self.get_book_title(book_title_slug)

        if book is None:
            return redirect(reverse('rango:index'))
        
        context_dict = {'form': form, 'book': book}
        return render(request, 'rango/leave_review.html', context_dict)
    
    @method_decorator(login_required)
    def post(self, request, book_title_slug):
        form = ReviewForm(request.POST)
        book = self.get_book_title(book_title_slug)

        if book is None:
            return redirect(reverse('rango:index'))
        
        if form.is_valid():
            review = form.save(commit=False)
            review.book = book
            review.upvotes = 0
            review.user = request.user
            review.save()

            return redirect(reverse('rango:show_book', kwargs={'book_title_slug': book_title_slug}))
        else:
            print(form.errors)
        
        context_dict = {'form': form, 'book': book}
        return render(request, 'rango/leave_review.html', context=context_dict)


class RegisterProfileView(View):
    @method_decorator(login_required)
    def get(self, request):
        form = UserProfileForm()
        context_dict = {'form': form}
        return render(request, 'rango/profile_registration.html', context_dict)
    
    @method_decorator(login_required)
    def post(self, request):
        form = UserProfileForm(request.POST, request.FILES)

        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return redirect(reverse('rango:index'))
        else:
            print(form.errors)
        
        context_dict = {'form': form}
        return render(request, 'rango/profile_registration.html', context_dict)


class ProfileView(View):
    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None
        
        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'picture': user_profile.picture,})
        reviews = Review.objects.filter(user = user.id)
        
        return (user, user_profile, form, reviews)
    
    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, user_profile, form, reviews) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rango:index'))
        
        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form,
                        'reviews': reviews}
        
        return render(request, 'rango/profile.html', context_dict)
    
    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (user, user_profile, form, reviews) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rango:index'))
        
        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)

        if form.is_valid():
            form.save(commit=True)
            return redirect('rango:profile', user.username)
        else:
            print(form.errors)
        
        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form,
                        'reviews': reviews}
        
        return render(request, 'rango/profile.html', context_dict)


class ListProfilesView(View):
    @method_decorator(login_required)
    def get(self, request):
        profiles = UserProfile.objects.all()
        return render(request,
                    'rango/list_profiles.html',
                    {'user_profile_list': profiles})


class LikeReviewView(View):
    @method_decorator(login_required)
    def get(self, request):
        review_id = request.GET['review_id']

        try:
            review = Review.objects.get(id=int(review_id))
        except Review.DoesNotExist:
            return HttpResponse(-1)
        except ValueError:
            return HttpResponse(-1)
        
        review.upvotes = review.upvotes + 1
        review.save()

        return HttpResponse(review.upvotes)


class DislikeReviewView(View):
    @method_decorator(login_required)
    def get(self, request):
        review_id = request.GET['review_id']

        try:
            review = Review.objects.get(id=int(review_id))
        except Review.DoesNotExist:
            return HttpResponse(-1)
        except ValueError:
            return HttpResponse(-1)
        
        review.upvotes = review.upvotes - 1
        review.save()

        return HttpResponse(review.upvotes)


class SearchResultsView(ListView):
    model = Book
    template_name = 'rango/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get("query").split()
        
        object_list = list()
        for word in query:
            title_results = list(Book.objects.filter(Q(title__icontains=word)))
            author_results = list(Book.objects.filter(Q(author__icontains=word)))
            isbn_results = list(Book.objects.filter(Q(isbn__icontains=word)))

            object_list += title_results + author_results + isbn_results

        return list(set(object_list))



def contact_us(request):
    return render(request, 'rango/contact_us.html')


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request,
                                               'last_visit',
                                               str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                        '%Y-%m-%d %H:%M:%S')
    if (datetime.now() - last_visit_time).seconds > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits


def search(request):
    context_dict = {}
    if request.method == 'POST':
        query = request.POST['query'].strip()

        if query:
            context_dict['result_list'] = run_query(query)
            context_dict['query'] = query
    return render(request, 'rango/search.html', context=context_dict)

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
About
{% endblock %}

{% block body_block %}
<div>
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">This is the About page.</h1>
                <h5>This is a website made by a group of students at the University of Glasgow to help book lovers discover new books to read!</h5>
            </div>
        </div>
    </div>
    <div>
        <p>Website visits: {{ visits }}</p>
    </div>
</div>
{% endblock %}

templates/rango/add_book.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Add Book
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a Book</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <form role="form" id="book_form" method="post" action="{% url 'rango:add_book' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}<br />
            {{ field }}<br />
            <div class="p-2"></div>
            {% endfor %}
            <br />
            <button class="btn btn-primary" type="submit" name="submit">
                Add Book
            </button>
            <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/books.ico' %}">
    <title>
        Books Are Fun - {% block title_block %}Reviews for Books!{% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
</head>

<body class="d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
            
            <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Books Are Fun</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item "><a class="nav-link" href="{% url 'rango:books' %}">Books</a></li>
                    <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
                    <li class="nav-item "><a class="nav-link" href="{% url 'rango:contact_us' %}">Contact Us</a></li>
                    <form class="form-inline" id="user-form" method="get" action="{% url 'rango:search_results' %}">
                        {% csrf_token %}
                
                        <div class="form-inline">
                            <input class="form-control" type="search" size="50" name="query" value="{{ query }}" id="query" placeholder="Enter book name..."/>
                        </div>
                
                        <button class="btn btn-primary" type="submit">Search</button>
                    </form>
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_book' %}">Add Book</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'rango:list_profiles' %}">List Profiles</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/">Logout</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <div class="container-fluid">
        <div class="row">
            <main role="main" class="col-md-auto  ml-sm-auto col-lg px-4">
                {% block body_block %}{% endblock %}
            </main>
        </div>
    </div>

    <!-- FOOTER -->
    <footer class="mt-auto">
        <hr style="width:85%">
        <div class="container">
            <div class="row">
                <div class="col-auto mr-auto">&copy; 2022 Books Are Fun &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></div>
                <div class="col-auto"><a href="#">Back to top</a></div>
            </div>
        </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'js/rango-jquery.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'js/rango-ajax.js' %}" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
</body>

</html>

templates/rango/book.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
{% if book %}
{{ book.title }}
{% else %}
Unknown Book
{% endif %}
{% endblock %}

{% block body_block %}
{% if book %}
<div class="jumbotron p-4">
    <div class="container">
        <h1>{{ book.title }}</h1>
        <h5>by {{ book.author }} (Author)</h5>
    </div>
</div>
<div class="container">
    <div class="row">
        <ul type="circle">
            <li>Score : {{ book.score }}</li>
            <li>ISBN : {{ book.isbn }}</li>
            <li>Publisher : {{ book.publisher }}</li>
            <li>Language : {{ book.language }}</li>
            <li>Price : £{{ book.price }}</li>
            <li>Description : {{ book.description }}</li>
        </ul>
    </div>
    <div class="row mb-2">
        <div class="col-md-2 themed-grid-col">Title</div>
        <div class="col-md-2 themed-grid-col">Rating</div>
        <div class="col-md-2 themed-grid-col">Comment</div>
        <div class="col-md-2 themed-grid-col">Publish Date</div>
        <div class="col-md-2 themed-grid-col">Upvotes</div> <br>
        <hr style="width:85%">
        {% if reviews %}
        {% for review in reviews %}
        <div class="col-md-2 themed-grid-col">{{ review.title }}</div>
        <div class="col-md-2 themed-grid-col">{{ review.rating }} out of 5 stars</div>
        <div class="col-md-2 themed-grid-col">{{ review.comment }}</div>
        <div class="col-md-2 themed-grid-col">{{ review.publishDate }}</div>
        <div class="col-md-2 themed-grid-col" id="like_count{{ review.id }}">{{ review.upvotes }}
            {% if user.is_authenticated %}
            <br>
            <button id="like_btn{{ review.id }}" data-reviewid="{{ review.id }}" class="btn btn-primary btn-sm like_btn"
                type="button">
                <span data-feather="thumbs-up"></span>
                Like
            </button>
            <button id="dislike_btn{{ review.id }}" data-reviewid="{{ review.id }}" class="btn btn-primary btn-sm dislike_btn"
                type="button">
                <span data-feather="thumbs-down"></span>
                Dislike
            </button>
            </br>
            {% endif %}
        </div>
        <hr style="width:85%">
        {% endfor %}
        {% else %}
        <strong>No reviews currently uploaded for this book.</strong>
        {% endif %}
    </div>

    {% if user.is_authenticated %}
    <a href="{% url 'rango:leave_review' book.slug %}"><Strong>Leave Review</Strong></a> <br>

    {% else %}
    <p>You have to be logged in to leave a review. <a href="/accounts/login/"> <Strong>Log in</Strong> </a> </p>
    {% endif %}

</div>
{% else %}
The specified book does not exist. Return to <a href="{% url 'rango:index' %}"><strong>Homepage</strong>.</a>
{% endif %}
{% endblock %}

templates/rango/contact_us.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Contact Us
{% endblock %}

{% block body_block %}
<div>
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">This is the Contact Us page.</h1>
                <div>
                    <h5>Information on how to contact will be made available soon.</h5><br />
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/rango/leave_review.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Leave Review
{% endblock %}


{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Leave Review</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <form role="form" id="review_form" method="post" action="{% url 'rango:leave_review' book.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
                    <div class="p-2"></div>
            {% endfor %}
            <br />
            <button class="btn btn-primary" type="submit" name="submit">
                Submit Review
                {{ book.updateScore }}
            </button>
            <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

templates/rango/profile.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
{{ selected_user.username }}'s Profile
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">{{ selected_user.username }}'s Profile</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        {% if user_profile.picture %}
        <img src="{{ MEDIA_URL }}{{ user_profile.picture }}" width="200" height="200"
            alt="{{ selected_user.username }}'s profile image" />
        {% else %}
        <img src="{% static 'images/anon.png' %}" width="200" height="200"
            alt="{{ selected_user.username }}'s profile image" />
        {% endif %}
        <br />
        <div>
            <p>
                <strong>Join date: {{ user_profile.joinDate }}</strong>
            </p>
            {% if selected_user == user %}
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Update" />
            </form>
            <br />
            <form action="{% url 'rango:delete_account' selected_user.username %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Delete Account</button>
            </form>
            <br />
            {% endif %}
        </div>

        <div class="col-md-6">
            <div class="card mb-6">
                <div class="card-body">
                    <h2>Reviews posted: {{ reviews.count }}</h2>
                    <p class="card-text">
                    <ul class="list-group">
                        {% for review in reviews %}
                        <li class="list-group-item">
                            <a href="{% url 'rango:show_book' review.book.slug %}">{{ review.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/rango/search_results.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Search
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
  <div class="container">
    <h1 class="jumbotron-heading">Search Results:</h1>
  </div>
</div>
<div>
  <ul>
    {% if object_list %}
      {% for book in object_list %}
        <li>
          <a href="{% url 'rango:show_book' book.slug %}">{{ book.title }}, {{ book.author }}</a>
        </li>
      {% endfor %}
    {% else %}
      {% if user.is_authenticated %}
        No match found. <a href="{% url 'rango:add_book' %}"><Strong>Add a new book to our website!</Strong></a>
      {% else %}
        No match found. <a href="{% url 'rango:register_profile' %}"><strong>Log in</strong></a> to add new books to our website. Alternatively, return to <a
        href="{% url 'rango:index' %}"><Strong>Homepage</Strong>.</a>
      {% endif %}
    {% endif %}
  </ul>
</div>
{% endblock %}